### PR TITLE
doc

### PR DESCRIPTION
**Pull request by LinxuanHu**

### CODE REVIEW

**Comment by reshnashrestha** [comment]
@LinxuanHu There is nothing on the file.

**Comment by LinxuanHu** [comment]
can you check the latest commit

**Comment by reshnashrestha** [comment]
image
@LinxuanHu You mean this?

**Comment by reshnashrestha** [comment]
Is this the final or what?

**Comment by LinxuanHu** [comment]
i'm still improving it, you can merge it first

**Pull request merged**
